### ISSUE TITLE
What is gain of polling versus classic jsonp?

### ISSUE THREAD

**Issue by ertrzyiks** [schibsted/sdk-js#10]
I noticed sdk use strange variant of jsonp, client expect script to define function which trigger callback. I can't see any gain, but i see some issues:

* with access to service you call ANY javascript code in users' browser
* lack of parallelism and maintaining queue

Is there any reason behind this solution?

Right now communication is based on response like:
```
function triggerResponse() {
   callback1234({ data: 1 })
}
```
and sdk polling on `triggerResponse` availability.

It could be:
```
callback1234({ data: 1 })
```

**Comment by PAkerstrand** [comment]
:+1:. Makes much more sense!

**Comment by joawan** [comment]
No gain. Change to a more JSONP true approach in 2.0.0
