### ISSUE TITLE
[v2.0] localstorage cache key should probably be client dependant

### ISSUE THREAD

**Issue by erikfried** [schibsted/sdk-js#16]
the localstorage key should have the client id in it, as the cookie storage key (the cookie name) does.

I think it should be possible for more than one client to operate on the same brower origin.

**Comment by thogra** [comment]
:point_up: Seems legit

**Comment by erikfried** [comment]
I have the solution ready, i think. Wait for PR

torsdag 5 november 2015 skrev thogra <notifications@github.com>:

**Comment by thogra** [comment]
@erikfried too slow, mister :wink:
