### ISSUE TITLE
[v2.0] Missing ability to override cache /enforce fresh reload from server

### ISSUE THREAD

**Issue by erikfried** [schibsted/sdk-js#19]
Our typical use-case for overriding the cache is when we know the user has just returned from spid (e g purhchase, login, logout) and thus is very likely to have a new state that should be reflected
 
As far as I can see right now the only way is to set `config.storage = 'standard'`, which would effectively disable caching.
This however has the drawback that the response is not saved in cache either. 

In pseudo code i think the solution could be quite simple, in `sdk-js.js`: 

```js
function hasSession(callback, forceFresh) {
 
  // ... other code
    
    if (forceFresh === true) {
        persist.clear();
    }

```
ping @thogra

**Comment by thogra** [comment]
The way to do this today would be to 
```
SPiD.sessionCache.clear();
SPiD.hasSession(callback);
```

I kinda like keeping the two separate

**Comment by erikfried** [comment]
@thogra ah, ok. Then I am happy.

**Comment by thogra** [comment]
:tophat:
