### ISSUE TITLE
Prevent concurrent hasSession requests (?)

### ISSUE THREAD

**Issue by erikfried** [schibsted/sdk-js#22]
It might not be uncommon to issue more than one request to `hasSession` almost at the same time, e g several components in a webpage might be interested in knowing the userId and asks for it.

As of now, if no cached response is present, each `hasSession` query will render a new request.

Unsure if this is by design or if it is worth improving?

proposed solution in PR #23

**Comment by erikfried** [comment]
After testing this in the current aftonbladet.se context i find we are making 5 such requests on each page load. - I guess we´d rather avoid these.

**Comment by danielbentes** [comment]
I’d say that it must be avoided.
