### ISSUE TITLE
Does the new SDK imply any changes on the flow depicted in http://techdocs.spid.no/login-flows/ ?

### ISSUE THREAD

**Issue by danielbentes** [schibsted/sdk-js#26]
If so then the documentation needs to be updated in order to reflect that.

**Comment by androa** [comment]
The [flowchart depicted on the JavaScript SDK](http://techdocs.spid.no/sdks/javascript/#auto-login-usecase) page is not consistent with the flowchart [explaining the login flow](http://techdocs.spid.no/login-flows/). 

The new flowchart no longer represent that the Client is responsible for initiating a local session.

**Comment by joawan** [comment]
Version 2 requires client to explicitly call hasSession, as init and hasSession has been split.
@danielbentes Can you update the PNGs?

**Comment by userpixel** [comment]
@danielbentes are the PNGs ☝️updated? Otherwise I might be able to help.
