### ISSUE TITLE
[Urgent!] Localstorage module clears *entire* localstorage

### ISSUE THREAD

**Issue by erikfried** [schibsted/sdk-js#29]
It uses the wrong localstorage api method, `clear` instead of `removeItem`.

The consequences can be quite catastrophical... 

PR coming up soon. 

> Storage.removeItem() takes a single argument — the key of the data item you want to remove — and removes it from the storage object for that domain.
Storage.clear() takes no arguments, and simply empties the entire storage object for that domain.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by thogra** [comment]
:scream:

**Comment by Andersos** [comment]
We have pulled in #30 and published a new version 2.1.1. How does it look?
We also deprecated 2.1.0 since it was the only version released to NPM before version 2.1.1.

**Comment by erikfried** [comment]
@Andersos :+1: I already deployed this fix last week, using our forked version.

I´ll check and integrate this new release tomorrow.

**Comment by Andersos** [comment]
Let me know if it works then we can close this issue =)

**Comment by erikfried** [comment]
will do

**Comment by joawan** [comment]
This is merged and can be closed right?
If not, just ping and we'll open it

**Comment by Andersos** [comment]
This can be closed yes.
