### ISSUE TITLE
Backwards breaking functionality/usage

### ISSUE THREAD

**Issue by danielbentes** [schibsted/sdk-js#33]
I've checked the documentation on initialisation of the script (http://techdocs.spid.no/sdks/javascript/#initialization-options) and comparing to the old JS SDK we now don't have the option to force trigger a hasSession request to SPiD anymore (status:true in old initialisation version). Is there a reason for that?

The use case is that some clients actually want to force a check on SPiD on a subsequent page load, but that is not possible if you already have done that and the result is stored on cookie/localstorage.

Is there a way to force the request and if so why is that not documented anywhere?

**Comment by thogra** [comment]
As I see it, there are a couple of ways to go about this:
A: Don't use a cache, set the init-option `{storage:false}`: 
B: Clear the cache before calling `hasSession`, see: http://techdocs.spid.no/sdks/js/api-docs/#sessionCacheClear

**Comment by danielbentes** [comment]
Or C: initiate the script with an option for forcing a automatic session request

**Comment by thogra** [comment]
> Or C: initiate the script with an option for forcing a automatic session request

I have a preference for having the SDK do one "thing" per method call, and only doing "a thing" when explicitly called. Doing an automatic session request on `init`, or keeping some sort of state in the SDK tracking if the next `hasSession` should bypass or clear the cache feels a bit complicated. On the other hand you've got to give the people what they want ...

**Comment by danielbentes** [comment]
Why not:
a) pass a second argument to hasSession so it can bypass the cache and poll the server?
b) add a argument to init?

This is still same logic as before, init does trigger a hassession on load, so this would just be ignoring cache every pageview.

**Comment by thogra** [comment]
We sure could do it like that @danielbentes. The reasoning behind *not* implementing it like it was in version 1.x was:  

> pass a second argument to hasSession so it can bypass the cache

Adding a "cache bypass" parameter seems redundant, given that a user can either not use the "session cache", or clear the session cache before calling `hasSession`. Passing a flag parameter would be doing more than one "thing", so I'd want to avoid it for that reason.

> add a argument to init

Again, I feel that we should stick to the single responsibility principle, all other things being equal (now, if there's a popular demand for adding such an option ... :smile: ). 

Anyway, these are just my 0.02$.

**Comment by danielbentes** [comment]
Given the 2 options you gave:
A: Don't use a storage/cache, set the init-option {storage:false}
B: Clear the storage/cache before calling hasSession

If you believe that both solve the usecase "As a client I want to check with SPiD which user is logged in as early as possible on pageview", then this needs to be explicitly documented as this is breaking functionality.

**Comment by joawan** [comment]
I agree with @thogra and we discussed this when implementing. The call should do one thing.
If you want to bypass cache on each page view (not sure why cause you might aswell not use cache), you first clear cache and then call hasSession.
