### ISSUE TITLE
'latest' version hosted on CDN

### ISSUE THREAD

**Issue by robborow** [schibsted/sdk-js#36]
Host a **latest** version of the js sdk on our CDN for clients to reference

**Comment by Andersos** [comment]
So this is what Joakim wrote about in https://github.com/schibsted/sdk-js/issues/32#issuecomment-172550361 I have not found any documentation yet of how to upload to unknown CDN.

**Comment by mikael-lindstrom** [comment]
This is part of the main SPiD platform repo, but there is a problem with having a latest version. Currently we don't do cache invalidations in CloudFront. Meaning a "latest" version would never update unless we do a manual cache invalidation. We would need to add this before we can implement a latest version.

**Comment by Andersos** [comment]
Do we track the progress on the cache validation somewhere I can follow?

**Comment by Andersos** [comment]
Relevant link thanks to @mikael-lindstrom http://techdocs.spid.no/sdks/js/hosting/

**Comment by robborow** [comment]
Let's simply invalidate using grunt as uploading to the CDN is already a grunt task. There are a couple of grunt plugins out there for cache invalidation (like https://github.com/CoSchedule/grunt-cloudfront-invalidate), if we don't want to write our own. Let's make sure we just target the one file. I'll take a look at this soon.

**Comment by joawan** [comment]
1) Do we have a use case for latest? That usually is a great way to end up with a broken site.

2) If you really need a latest, upload that as usual but set a shorter cache header. No need for invalidations.

**Comment by robborow** [comment]
To name two very specific use cases:

- To prevent tasks such as "Update sites and apps to use latest version of SPID SDKs" as seen in the new T&C project https://docs.google.com/spreadsheets/d/1wJ8Xz2LIZuFTBqVy3UoPiqLOifhv8H5OaaEPNwxOOOk

- For easier maintainability for clients such as Viktklubb, that currently don't have a single developer and consequently even a simple task such as updating the sdk version can be costly and time consuming

**Comment by joawan** [comment]
Linking internal docs and plans on a public github is not very good. Especially as that document is readable by anyone...

Using a latest version in production is strongly discouraged. Each new version change can break your implementation or entire service.

**Comment by Andersos** [comment]
I agree with Joakim. I don't think we should recommend clients to use latest version in production because of reasons stated.

**Comment by robborow** [comment]
That wasn't an internal doc and no secrets there really, especially since like you said it was made publicly available, but this is a topic for elsewhere imo :)

If you think we will release broken versions or backwards incompatible versions without communicating this with our clients, then that's a valid point but I think that is something we are trying to avoid today already, if not, we should at all costs.

I'm saying we could have this as an alternative for clients that this use case is applicable to and where the risk is worth to take.

I'm not trying to being adamant, sorry if I come across as it, I'm just trying to provide some arguments for this before we make a decision.

**Comment by danielbentes** [comment]
Most of the changes introduced by a new library should be backwards compatible, but there might be a few behavior changes now and then, even for a mature script that developers should be made aware of. 

Our JS SDK is not mature enough yet, meaning we will introduce new functionality and changes. So I agree with Joakim on not introducing the latest concept at the moment. But I also see the need for it.

What we could introduce is a combination:
- major version changes as new script
- sub version changes as latest

This would give us:
- js-sdk-v2-latest.js, which would be the latest for all versions within 2.x 
- js-sdk-v2.2.js, which would be a specific version

All changes within a major version MUST be backwards compatible, while a major change would require the clients to upgrade with care... To js-sdk-v3-latest.js for example... ;)
