### ISSUE TITLE
Grunt clean task is not working if files exist in directory

### ISSUE THREAD

**Issue by joawan** [schibsted/sdk-js#41]
Running build twice in a row does not work due to clean task not working properly.

**Comment by robborow** [comment]
Hmm, cannot reproduce, works as expected for me

**Comment by Andersos** [comment]
For me if your run the comman `npm run build` it deletes the folder called `dist` then remakes it. Maybe you want the clean taks to do something else. What do you mean with not working properly?

![dist](https://cloud.githubusercontent.com/assets/288977/13363876/1c9575f2-dccc-11e5-8c3b-d83304e1922c.gif)

**Comment by joawan** [comment]
Working for me too know. No idea what cause the error.
