### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kjarmicki** [schibsted/sdk-js#42]
Hi,

Since https://github.com/schibsted/sdk-js/pull/37 was pulled in, could you bump version number to indicate change and release it?

cc @joawan

**Comment by joawan** [comment]
Sorry, waited for another patch to put into the release.
That is not done yet, so I guess we will release that later.

Bumping now.

**Comment by joawan** [comment]
New version is now available

**Comment by kjarmicki** [comment]
Thanks! :)
