### ISSUE TITLE
Difference in login urls?

### ISSUE THREAD

**Issue by kjarmicki** [schibsted/sdk-js#44]
Hi,

I've noticed that SPiD SKD 1.7 generates urls like ```https://payment.schibsted.no/flow/login?response_type=code&client_id...```
while in 2.1 they're like ```https://payment.schibsted.no/login?response_type=code&flow=signup&client_id...```

Can lack of /flow/ in 2.1 have significant implications in login process and/or visibility of user's products? We're experiencing trouble trying to migrate to 2.1.

**Comment by Andersos** [comment]
What patch version are you using? Are you talking about version 2.1.0 or 2.1.2? Do you experience the same problem on version 2.0.0? Are you trying to migrate from 1.7 to 2.1.2?

**Comment by kjarmicki** [comment]
@Andersos We're migrating from 1.7.9 to 2.1.2, as far as I can tell flow was changed in 1.7.7 ( https://github.com/schibsted/sdk-js/commit/466967cc3461c14799e61be9971cf3d72d85aacf ) but this change wasn't propagated to 2.x and this module https://github.com/schibsted/sdk-js/blob/master/src/spid-uri.js builds urls like SPiD before 1.7.7

**Comment by linnhege** [comment]
I have found the bug and you guys are correct, the new version doesn't generate new flow links. I will create a PR for this asap :)

**Comment by kjarmicki** [comment]
cool, thanks @linnhege :)

**Comment by linnhege** [comment]
A fix is merged and will probably be released today.
