### ISSUE TITLE
Calling parent 

### ISSUE THREAD

**Issue by sgulseth** [schibsted/sdk-js#5]
Calling window.parent may result in SecurityError if the script is inside an iframe on another domain.
Is it necessary to notify the parent document on response? 

https://github.com/schibsted/sdk-js/blob/master/src/spid-sdk.js#L260

**Comment by wojniemiec** [comment]
Can you explain me, why running sdk in an iframe is not allowed? We also experience problems with SecurityError because of calling window.parent. Do you possibly have plans to remove calls to window.parent?

**Comment by joawan** [comment]
Removed in 2.0.0 version
