### ISSUE TITLE
Use encodeURI instead of encodeURIComponent

### ISSUE THREAD

**Issue by userpixel** [schibsted/sdk-js#65]
In `spid-uri` we encode all `redirect_uri`s with `encodeURIComponent`. There is a [subtle difference](https://coderwall.com/p/y347ug/encodeuri-vs-encodeuricomponent) between `encodeURIComponent` and `encodeURI`. The latter is intended for full URIs and should be used in our case.

*Note: In the `spid-hassession? backend we correctly use `decodeURI`.*

**Comment by joawan** [comment]
I think we need to actually use component, as it is a get param

**Comment by userpixel** [comment]
You were right, the whole url was a component 👍
