### ISSUE TITLE
Prevent apache access logs from being distributed to NPM

### ISSUE THREAD

**Issue by userpixel** [schibsted/sdk-js#67]
<img width="733" alt="screen shot 2016-12-29 at 20 28 48" src="https://cloud.githubusercontent.com/assets/835750/21552946/729f4a7e-ce05-11e6-960e-ca06f4284216.PNG">

This is probably not needed by the users of `spid-sdk-js` so add them to `.npmignore`.

**Comment by joawan** [comment]
Those should not be there. Someone made a publish from a dirty state.
