### ISSUE TITLE
Room for improvement - bad condition syntax

### ISSUE THREAD

**Issue by userpixel** [schibsted/sdk-js#95]
In https://github.com/schibsted/sdk-js/blob/master/src/spid-cookie.js#L38 : 

```javascript
    if(session.sp_id &&
        (options.setVarnishCookie === true ||
        (options.storage === 'cookie' && options.setVarnishCookie !== false))) {
        _setVarnishCookie(session, options);
    }
```

The third condition in the if statement is error prone.

* It is not necessary if `options.setVarnishCookie` is true (second condition).
* If `options.setVarnishCookie` is anything other than false (including `null` and even `undefined` which is likely if that option is not passed to the constructor). It'll probably not do what it is intended to do.

**Comment by userpixel** [comment]
Update: one test case in `spid-sdk_test.js` reads as:

> SPiD.hasSession should set SP_ID cookie when cookies are used and setVarnishCookie option is not set

So maybe it is the desired effect but the code still looks like an error.

**Comment by kjarmicki** [comment]
The reason behind using the null value in `setVarnishCookie` by default was backwards compatibility -> https://github.com/schibsted/sdk-js/pull/37
